import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/styles/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          light: '#FF8A52',
          dark: '#E55A1B',
          soft: '#FFF4EE',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          soft: '#FFF4EE',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        // Design system tokens
        surface: {
          DEFAULT: '#FFFFFF',
          subtle: '#F4F2EE',
          raised: '#F8F7F4',
        },
        brand: {
          DEFAULT: '#FF6B2B',
          light: '#FF8A52',
          dark: '#E55A1B',
          soft: '#FFF4EE',
          glow: 'rgba(255, 107, 43, 0.28)',
        },
        ink: {
          DEFAULT: '#1A1A18',
          1: '#1A1A18',
          2: '#6B6B63',
          3: '#A8A89E',
        },
        success: {
          DEFAULT: '#16A34A',
          soft: '#DCFCE7',
          bg: '#DCFCE7',
        },
        warning: {
          DEFAULT: '#D97706',
          soft: '#FEF3C7',
          bg: '#FEF3C7',
        },
        error: {
          DEFAULT: '#DC2626',
          soft: '#FEE2E2',
          bg: '#FEE2E2',
        },
        info: {
          DEFAULT: '#2563EB',
          soft: '#EFF6FF',
          bg: '#EFF6FF',
        },
        special: {
          DEFAULT: '#7C3AED',
          soft: '#F5F3FF',
          bg: '#F5F3FF',
        },
        'border-strong': 'rgba(0,0,0,0.12)',
        'border-light': 'rgba(0,0,0,0.07)',
        dark: {
          DEFAULT: '#1A1A18',
          soft: '#2A2A28',
          subtle: '#3A3A36',
        },
        apple: {
          separator: '#F0EEEA',
        },
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
      },
      fontFamily: {
        display: ['var(--font-fraunces)', 'Fraunces', 'Georgia', 'serif'],
        body: ['var(--font-dm-sans)', 'DM Sans', '-apple-system', 'BlinkMacSystemFont', "'SF Pro Display'", "'Segoe UI'", 'system-ui', 'sans-serif'],
        mono: ['var(--font-dm-mono)', 'DM Mono', "'SF Mono'", "'Fira Code'", 'monospace'],
        system: [
          "var(--font-dm-sans)",
          "-apple-system",
          "BlinkMacSystemFont",
          "'SF Pro Display'",
          "'Segoe UI'",
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        '2xs': '11px',
        'xs-system': ['11px', { lineHeight: '1.4', letterSpacing: '0.02em' }],
        'sm-system': ['13px', { lineHeight: '1.45', letterSpacing: '0.01em' }],
        'base-system': ['15px', { lineHeight: '1.5', letterSpacing: '0' }],
        'md-system': ['17px', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '500' }],
        'lg-system': ['22px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'xl-system': ['28px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        '2xl-system': ['34px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '600' }],
        hero: ['56px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '600' }],
        h1: ['36px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        h2: ['28px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '500' }],
        h3: ['20px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['17px', { lineHeight: '1.5', letterSpacing: '0' }],
        'body-base': ['15px', { lineHeight: '1.5', letterSpacing: '0' }],
        caption: ['13px', { lineHeight: '1.45', letterSpacing: '0.01em' }],
        price: ['18px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
      },
      letterSpacing: {
        'tightest': '-0.04em',
        'tighter': '-0.03em',
        'tight': '-0.02em',
        'snug': '-0.01em',
        'wide': '0.01em',
        'wider': '0.02em',
        'widest': '0.08em',
        'letterpress': '0.15em',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'card': '20px',
        'card-lg': '24px',
        'sheet': '24px',
        'input': '14px',
        'pill': '9999px',
        'badge': '8px',
        'tag': '8px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.08), 0 2px 6px rgba(0,0,0,0.05)',
        'fab': '0 4px 16px rgba(0,0,0,0.2)',
        'accent-glow': '0 8px 24px rgba(255, 107, 43, 0.28)',
        'accent-cta': '0 4px 14px rgba(255, 107, 43, 0.3)',
        'dark-elevated': '0 8px 24px rgba(0,0,0,0.2), 0 2px 8px rgba(0,0,0,0.1)',
        'toggle': '0 2px 4px rgba(0,0,0,0.15)',
        'input-focus': '0 0 0 4px rgba(255, 107, 43, 0.1)',
        'accent-pulse': '0 4px 12px rgba(255, 107, 43, 0.3)',
        'stamp': '0 4px 8px rgba(0,0,0,0.15)',
        'toast': '0 8px 24px rgba(0,0,0,0.15)',
        'sheet': '0 -4px 32px rgba(0,0,0,0.12)',
        'modal': '0 20px 60px rgba(0,0,0,0.15)',
      },
      animation: {
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'slide-up': 'sheet-enter 320ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'fade-in': 'fade-in 200ms cubic-bezier(0.4, 0, 0.2, 1)',
        'page-enter': 'page-enter 320ms cubic-bezier(0, 0, 0.2, 1) both',
        'btn-press': 'btn-press 120ms cubic-bezier(0.4, 0, 0.2, 1)',
        'cart-add': 'cart-add 200ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'tab-spring': 'tab-spring 200ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
        'pulse-accent': 'pulse-accent-ring 1.5s ease-in-out infinite',
        'error-shake': 'error-shake 400ms cubic-bezier(0.4, 0, 0.2, 1)',
        'scale-in': 'scale-in 400ms cubic-bezier(0, 0, 0.2, 1) 0.3s both',
        'checkmark-draw': 'checkmark-draw 600ms cubic-bezier(0, 0, 0.2, 1) forwards',
        'success-scale': 'success-scale 600ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'cart-float-in': 'cart-float-in 320ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'confetti-fall': 'confetti-fall 4s linear forwards',
        'stamp-drop': 'stamp-drop 500ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'spring-pop': 'spring-pop 400ms cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'sheet-enter': {
          from: { transform: 'translateY(60px)', opacity: '0.8' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'page-enter': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'btn-press': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.97)' },
          '100%': { transform: 'scale(1)' },
        },
        'cart-add': {
          '0%': { transform: 'scale(1)' },
          '40%': { transform: 'scale(1.2)' },
          '100%': { transform: 'scale(1)' },
        },
        'tab-spring': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(1.3)' },
        },
        'pulse-accent-ring': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(255, 107, 43, 0.4)' },
          '50%': { boxShadow: '0 0 0 12px rgba(255, 107, 43, 0)' },
        },
        'error-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
        'scale-in': {
          from: { transform: 'scale(0.9)', opacity: '0' },
          to: { transform: 'scale(1)', opacity: '1' },
        },
        'checkmark-draw': {
          from: { strokeDashoffset: '24' },
          to: { strokeDashoffset: '0' },
        },
        'success-scale': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '60%': { transform: 'scale(1.05)', opacity: '1' },
          '100%': { transform: 'scale(1)' },
        },
        'cart-float-in': {
          from: { transform: 'translateX(-50%) translateY(80px)', opacity: '0' },
          to: { transform: 'translateX(-50%) translateY(0)', opacity: '1' },
        },
        'confetti-fall': {
          '0%': { transform: 'translateY(-10vh) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(105vh) rotate(720deg)', opacity: '0' },
        },
        'stamp-drop': {
          '0%': { transform: 'translateY(-30px) rotate(-15deg)', opacity: '0' },
          '60%': { transform: 'translateY(4px) rotate(3deg)', opacity: '1' },
          '100%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
        },
        'spring-pop': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '70%': { transform: 'scale(1.05)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      maxWidth: {
        'content': '390px',
        'content-md': '480px',
        'content-lg': '540px',
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
export default config;
